# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Spring Boot & Gradle CI/CD

# 이벤트 트리거
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  S3_BUCKET_NAME: elasticbeanstalk-ap-northeast-2-526437230846

jobs:
  build:
    # 실행환경
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # 자바 버전 설정 스프링 3.0 이후부터 java17이 최소 요구사항
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    # gradlew 실행 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    # gradle build
    - name: Build with Gradle
      # 테스트를 스킵하고 빌드 시도
      run: ./gradlew clean build --exclude-task test
    # 디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy
    # Jar 파일 복사
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy
    - name: Make zip file
      run: zip -r ./coinTalk.zip ./deploy
      shell: bash
    # IAM 인증
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    # S3로 coinTalk파일 보내기
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./coinTalk.zip s3://$S3_BUCKET_NAME/